image: node:18-bullseye-slim

stages:
  - lint
  - test
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "staging"

lint-server:
  stage: lint 
  script:
    - cd server && ./node_modules/eslint/bin/eslint.js --ext js,mjs,cjs . 
  allow_failure: false

lint-client:
  stage: lint 
  script:
    - pwd
    - ls -al
    - cd client && ./node_modules/eslint/bin/eslint.js --ext js,jsx,mjs,cjs .
  allow_failure: false

server-side-test:
  stage: test
  script:
    - npm run test

client-side-build:
  stage: build
  script:
    - cd client && npm run build
  only:
    refs:
      - staging
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - client/build
